import streamlit as st
from datetime import datetime
import api_client
import requests as http_requests


def search_crl():

    # ── Back button (with top margin to avoid Streamlit toolbar overlap) ──
    st.markdown("<div style='margin-top:60px'></div>", unsafe_allow_html=True)
    if st.button("← Back to Dashboard"):
        st.session_state.current_feature = None
        st.rerun()

    st.divider()

    st.title("🗒️ Certificate Revocation List (CRL)")
    st.markdown("View the current Certificate Revocation List for this CA")
    st.divider()

    # ── Fetch CRL from backend ──
    crl_pem = None
    try:
        result = api_client.get_crl()
        crl_pem = result.get("crl_pem", "")
    except http_requests.ConnectionError:
        st.error("❌ Cannot connect to backend.")
    except http_requests.HTTPError as e:
        if e.response is not None and e.response.status_code == 404:
            st.warning("⚠️ No CRL has been generated yet. Ask an admin to generate the CRL first.")
        else:
            st.error(f"Backend error: {e}")

    tab1, tab2 = st.tabs(["📋 CRL Content", "📊 CRL Information"])

    with tab1:
        st.subheader("Certificate Revocation List (PEM)")

        if crl_pem:
            st.markdown("**📄 CRL (PEM format):**")
            st.markdown(f"""
            <div style="background-color: #1a1a1a; color: #e0e0e0; padding: 15px; border-radius: 5px; font-family: monospace; overflow-x: auto; max-height: 400px; overflow-y: auto;">
            <pre style="margin: 0; white-space: pre-wrap; word-wrap: break-word;">{crl_pem}</pre>
            </div>
            """, unsafe_allow_html=True)

            st.divider()

            col1, col2 = st.columns(2)
            with col1:
                st.download_button(
                    label="📥 Download CRL (PEM)",
                    data=crl_pem,
                    file_name="revocation_list.pem",
                    mime="application/x-pem-file",
                    use_container_width=True
                )
            with col2:
                # Also offer DER-like download as binary (simplified)
                st.info("💡 To use in applications, download the PEM file and import into your trust store.")

        else:
            st.info("No CRL data available. The CRL will appear here once generated by an admin.")

    with tab2:
        st.subheader("CRL Information")

        col1, col2 = st.columns(2)

        with col1:
            st.markdown("**ℹ️ CRL Details:**")
            st.markdown(f"""
            <div style="background-color: #2d3748; border-left: 4px solid #4299e1; border-radius: 5px; padding: 15px; margin: 15px 0;">
            <div style="color: #e0e0e0; font-size: 14px;">
            <div style="margin: 5px 0;"><strong>CRL Status:</strong> {"✅ Available" if crl_pem else "❌ Not Generated"}</div>
            <div style="margin: 5px 0;"><strong>Format:</strong> PEM (X.509 CRL)</div>
            <div style="margin: 5px 0;"><strong>Last Checked:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</div>
            <div style="margin: 5px 0;"><strong>Standard:</strong> RFC 5280</div>
            </div>
            </div>
            """, unsafe_allow_html=True)

        with col2:
            st.markdown("**📖 About CRL:**")
            st.markdown("""
            A **Certificate Revocation List (CRL)** is a list of digital certificates 
            that have been revoked by the issuing Certificate Authority (CA) before 
            their scheduled expiration date.

            - Applications check the CRL to verify certificate validity
            - Updated by the CA whenever a certificate is revoked
            - Should be checked regularly for current validity status
            - Alternative to OCSP (Online Certificate Status Protocol)
            """)

        st.divider()

        if crl_pem:
            # Count rough line count as a proxy for CRL entries
            pem_lines = crl_pem.count("\n")
            col1, col2, col3 = st.columns(3)
            with col1:
                st.metric("📄 CRL Size", f"{len(crl_pem)} bytes")
            with col2:
                st.metric("📅 Last Retrieved", datetime.now().strftime('%H:%M:%S'))
            with col3:
                st.metric("✅ Format", "PEM")
