import streamlit as st
from datetime import datetime
import api.api_client as api_client
import requests as http_requests
from views._cert_display import render_certificate


def search_crl():

    st.markdown("<div style='margin-top:60px'></div>", unsafe_allow_html=True)
    if st.button("← Back to Dashboard"):
        st.session_state.current_feature = None
        st.rerun()

    st.divider()
    st.title("🗒️ Certificate Revocation List (CRL)")
    st.markdown(
        "View the current CRL issued by this CA and inspect any revoked certificate."
    )
    st.divider()

    # ── Fetch CRL PEM ─────────────────────────────────────────────────────────
    crl_pem  = None
    crl_error = None
    try:
        result   = api_client.get_crl()
        crl_pem  = result.get("crl_pem", "")
    except http_requests.ConnectionError:
        crl_error = "❌ Cannot connect to backend."
    except http_requests.HTTPError as e:
        if e.response is not None and e.response.status_code == 404:
            crl_error = "⚠️ No CRL has been generated yet. Ask an admin to generate the CRL first."
        else:
            crl_error = f"Backend error: {e}"

    # ── Fetch REVOKED certificates (system-wide, no admin required) ───────────
    revoked_certs = []
    try:
        revoked_certs = api_client.get_revoked_certificates()
    except Exception:
        pass  # Non-fatal – inspector tab will show empty state

    tab1, tab2, tab3 = st.tabs(["📋 CRL Content", "🔍 Inspect Revoked Certificate", "📊 About CRL"])

    # ═══ TAB 1 — raw CRL PEM ══════════════════════════════════════════════════
    with tab1:
        st.subheader("Certificate Revocation List (PEM)")

        if crl_error:
            st.warning(crl_error)
        elif crl_pem:
            st.markdown("**📄 CRL (PEM format):**")
            st.markdown(f"""
            <div style="background-color: #1a1a1a; color: #e0e0e0; padding: 15px; border-radius: 5px;
                        font-family: monospace; overflow-x: auto; max-height: 400px; overflow-y: auto;">
            <pre style="margin: 0; white-space: pre-wrap; word-wrap: break-word;">{crl_pem}</pre>
            </div>
            """, unsafe_allow_html=True)

            st.divider()

            col1, col2 = st.columns(2)
            with col1:
                st.download_button(
                    label="📥 Download CRL (PEM)",
                    data=crl_pem,
                    file_name="revocation_list.pem",
                    mime="application/x-pem-file",
                    use_container_width=True,
                )
            with col2:
                st.metric("📄 CRL Size", f"{len(crl_pem):,} bytes")
        else:
            st.info("No CRL data available. The CRL will appear here once generated by an admin.")

    # ═══ TAB 2 — revoked certificate inspector ════════════════════════════════
    with tab2:
        st.subheader("Inspect a Revoked Certificate")
        st.markdown(
            "Select a revoked certificate to view its full structured details. "
            "The certificate PEM is parsed on the server — only structured fields are sent to you."
        )

        if not revoked_certs:
            st.info("✅ No revoked certificates in the system.")
        else:
            # Dropdown label: Cert ID | Revoked | validity range
            cert_options = [
                f"#{c['id']}  REVOKED  —  "
                f"{str(c.get('valid_from', ''))[:10]} → {str(c.get('valid_to', ''))[:10]}"
                for c in revoked_certs
            ]

            selected_idx = st.selectbox(
                "Select a revoked certificate:",
                range(len(revoked_certs)),
                format_func=lambda i: cert_options[i],
                key="crl_cert_select",
            )

            selected_cert = revoked_certs[selected_idx]

            st.divider()

            # ── Fetch parsed info from BE (uses customer /certificates/{id}/info) ──
            info_key = f"crl_cert_info_{selected_cert['id']}"
            if info_key not in st.session_state:
                with st.spinner("Parsing certificate on server..."):
                    try:
                        st.session_state[info_key] = api_client.get_certificate_info(
                            selected_cert["id"]
                        )
                    except http_requests.HTTPError as e:
                        st.error(f"❌ Could not parse certificate: {e}")
                        st.session_state[info_key] = None
                    except http_requests.ConnectionError:
                        st.error("❌ Cannot connect to backend.")
                        st.session_state[info_key] = None

            info = st.session_state.get(info_key)
            if info:
                render_certificate(info, selected_cert)
            else:
                st.warning("Certificate information could not be loaded.")

    # ═══ TAB 3 — about CRL ════════════════════════════════════════════════════
    with tab3:
        st.subheader("CRL Information")

        col1, col2 = st.columns(2)
        with col1:
            st.markdown("**ℹ️ CRL Details:**")
            st.markdown(f"""
            <div style="background-color: #2d3748; border-left: 4px solid #4299e1;
                        border-radius: 5px; padding: 15px; margin: 15px 0;">
            <div style="color: #e0e0e0; font-size: 14px;">
            <div style="margin: 5px 0;"><strong>CRL Status:</strong> {"✅ Available" if crl_pem else "❌ Not Generated"}</div>
            <div style="margin: 5px 0;"><strong>Format:</strong> PEM (X.509 CRL)</div>
            <div style="margin: 5px 0;"><strong>Last Checked:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</div>
            <div style="margin: 5px 0;"><strong>Standard:</strong> RFC 5280</div>
            <div style="margin: 5px 0;"><strong>Total Revoked:</strong> {len(revoked_certs)} certificate(s)</div>
            </div>
            </div>
            """, unsafe_allow_html=True)

        with col2:
            st.markdown("**📖 About CRL:**")
            st.markdown("""
            A **Certificate Revocation List (CRL)** is a list of digital certificates
            that have been revoked by the issuing Certificate Authority (CA) before
            their scheduled expiration date.

            - Applications check the CRL to verify certificate validity
            - Updated by the CA whenever a certificate is revoked
            - Should be checked regularly for current validity status
            - Alternative to OCSP (Online Certificate Status Protocol)
            """)

        if crl_pem:
            st.divider()
            col1, col2, col3 = st.columns(3)
            with col1:
                st.metric("📄 CRL Size", f"{len(crl_pem):,} bytes")
            with col2:
                st.metric("📅 Last Retrieved", datetime.now().strftime('%H:%M:%S'))
            with col3:
                st.metric("🚫 Revoked", len(revoked_certs))
